import { useState } from "react";
import { useQuery,useQueryClient,useMutation } from "@tanstack/react-query";
import { adminService } from "@/services/adminService";
import { useToast } from "@/components/ui/use-toast";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Users,FileText,MessageSquare,Database,Trash2,ShieldCheck,Sparkles } from "lucide-react";
import { formatFileSize } from "@/utils/date";
const TABS=[{key:"analytics",label:"Analytics"},{key:"users",label:"Users"},{key:"documents",label:"Documents"}];
export default function AdminPanel(){const [tab,setTab]=useState("analytics");return <div className="page-enter max-w-[1500px] mx-auto p-4 sm:p-6 lg:p-8 space-y-6"><section className="relative overflow-hidden rounded-[28px] border bg-card p-6 sm:p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_90%_10%,hsl(var(--primary)/.12),transparent_30%),radial-gradient(circle_at_20%_100%,hsl(158_55%_55%/.08),transparent_28%)]"/><div className="relative flex items-end justify-between gap-4"><div><div className="inline-flex items-center gap-2 text-xs font-bold text-primary"><ShieldCheck className="h-3.5 w-3.5"/> Control center</div><h1 className="text-4xl font-black tracking-[-.045em] mt-2">Admin workspace.</h1><p className="text-muted-foreground mt-2">Monitor users, knowledge sources and system activity.</p></div><Sparkles className="hidden sm:block h-8 w-8 text-primary"/></div></section><div className="inline-flex rounded-2xl border bg-card p-1 gap-1">{TABS.map(t=><button key={t.key} onClick={()=>setTab(t.key)} className={`rounded-xl px-4 py-2.5 text-sm font-bold transition-all ${tab===t.key?"bg-foreground text-background shadow":"text-muted-foreground hover:text-foreground"}`}>{t.label}</button>)}</div>{tab==="analytics"&&<AnalyticsTab/>}{tab==="users"&&<UsersTab/>}{tab==="documents"&&<DocumentsTab/>}</div>}
function AnalyticsTab(){const {data,isLoading}=useQuery({queryKey:["admin","analytics"],queryFn:()=>adminService.getAnalytics()});if(isLoading)return <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[...Array(4)].map((_,i)=><Skeleton key={i} className="h-32 rounded-2xl"/>)}</div>;const a=data?.data;const cards=[{label:"Total Users",value:a?.totalUsers,icon:Users},{label:"Total Documents",value:a?.totalDocuments,icon:FileText},{label:"Total Chunks",value:a?.totalChunks,icon:Database},{label:"Questions Asked",value:a?.totalQuestions,icon:MessageSquare}];return <div className="space-y-5"><div className="grid grid-cols-2 xl:grid-cols-4 gap-4 stagger">{cards.map(({label,value,icon:Icon})=><Card key={label} className="surface-card lift"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="text-3xl font-black mt-2">{value??0}</p></div><div className="h-10 w-10 rounded-xl bg-secondary flex items-center justify-center"><Icon className="h-4 w-4 text-secondary-foreground"/></div></div></CardContent></Card>)}</div><Card className="surface-card"><CardHeader><CardTitle>Document status</CardTitle><p className="text-sm text-muted-foreground">Current processing state across the system.</p></CardHeader><CardContent className="flex gap-2 flex-wrap">{a?.documentStatusBreakdown?.map(s=><Badge key={s._id} variant="outline" className="rounded-full capitalize px-3 py-1">{s._id}: {s.count}</Badge>)}</CardContent></Card></div>}
function UsersTab(){const qc=useQueryClient();const {toast}=useToast();const {data,isLoading}=useQuery({queryKey:["admin","users"],queryFn:()=>adminService.getUsers({limit:50})});const del=useMutation({mutationFn:id=>adminService.deleteUser(id),onSuccess:()=>{qc.invalidateQueries({queryKey:["admin","users"]});toast({title:"User deleted"})},onError:e=>toast({variant:"destructive",title:"Delete failed",description:e.response?.data?.message})});if(isLoading)return <Skeleton className="h-64 w-full rounded-2xl"/>;const users=data?.data?.users||[];return <div className="surface-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted/45 text-xs uppercase text-muted-foreground"><tr><th className="py-4 px-5">Name</th><th className="py-4 px-5">Email</th><th className="py-4 px-5">Role</th><th className="py-4 px-5">Joined</th><th className="py-4 px-5 text-right">Actions</th></tr></thead><tbody>{users.map(u=><tr key={u._id} className="border-t hover:bg-muted/35 transition-colors"><td className="py-4 px-5 font-semibold">{u.name}</td><td className="py-4 px-5 text-muted-foreground">{u.email}</td><td className="py-4 px-5"><Badge variant={u.role==="admin"?"default":"secondary"} className="capitalize rounded-full">{u.role}</Badge></td><td className="py-4 px-5 text-muted-foreground">{new Date(u.createdAt).toLocaleDateString()}</td><td className="py-4 px-5 text-right">{u.role!=="admin"&&<Button variant="ghost" size="icon" className="rounded-xl hover:bg-destructive/10" onClick={()=>del.mutate(u._id)}><Trash2 className="h-4 w-4 text-destructive"/></Button>}</td></tr>)}</tbody></table></div></div>}
function DocumentsTab(){const qc=useQueryClient();const {toast}=useToast();const {data,isLoading}=useQuery({queryKey:["admin","documents"],queryFn:()=>adminService.getDocuments({limit:50})});const del=useMutation({mutationFn:id=>adminService.deleteDocument(id),onSuccess:()=>{qc.invalidateQueries({queryKey:["admin","documents"]});toast({title:"Document deleted"})}});if(isLoading)return <Skeleton className="h-64 w-full rounded-2xl"/>;const docs=data?.data?.documents||[];return <div className="surface-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted/45 text-xs uppercase text-muted-foreground"><tr><th className="py-4 px-5">Name</th><th className="py-4 px-5">Owner</th><th className="py-4 px-5">Size</th><th className="py-4 px-5">Status</th><th className="py-4 px-5 text-right">Actions</th></tr></thead><tbody>{docs.map(d=><tr key={d._id} className="border-t hover:bg-muted/35 transition-colors"><td className="py-4 px-5 font-semibold">{d.originalName}</td><td className="py-4 px-5 text-muted-foreground">{d.owner?.email}</td><td className="py-4 px-5 text-muted-foreground">{formatFileSize(d.fileSize)}</td><td className="py-4 px-5"><Badge variant="outline" className="capitalize rounded-full">{d.status}</Badge></td><td className="py-4 px-5 text-right"><Button variant="ghost" size="icon" className="rounded-xl hover:bg-destructive/10" onClick={()=>del.mutate(d._id)}><Trash2 className="h-4 w-4 text-destructive"/></Button></td></tr>)}</tbody></table></div></div>}
